// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVr_prcMzTLOPYU8Y3h3g2AWRn_SrYggw',
    appId: '1:317038982664:web:2006bc3d1821f4e96683bd',
    messagingSenderId: '317038982664',
    projectId: 'unionshop-a95a8',
    authDomain: 'unionshop-a95a8.firebaseapp.com',
    storageBucket: 'unionshop-a95a8.firebasestorage.app',
    measurementId: 'G-H6PFS99EVJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgyJufcW1CElzh4STflX-5pWyAoOuIYCs',
    appId: '1:317038982664:android:e6d6059164b80baf6683bd',
    messagingSenderId: '317038982664',
    projectId: 'unionshop-a95a8',
    storageBucket: 'unionshop-a95a8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrZiBvz_eimdUabl5fNqxdrFPQeDXmdyo',
    appId: '1:317038982664:ios:4c5fda7cec8e55c96683bd',
    messagingSenderId: '317038982664',
    projectId: 'unionshop-a95a8',
    storageBucket: 'unionshop-a95a8.firebasestorage.app',
    iosBundleId: 'com.example.unionShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrZiBvz_eimdUabl5fNqxdrFPQeDXmdyo',
    appId: '1:317038982664:ios:4c5fda7cec8e55c96683bd',
    messagingSenderId: '317038982664',
    projectId: 'unionshop-a95a8',
    storageBucket: 'unionshop-a95a8.firebasestorage.app',
    iosBundleId: 'com.example.unionShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVr_prcMzTLOPYU8Y3h3g2AWRn_SrYggw',
    appId: '1:317038982664:web:74beeadc3f26cfd26683bd',
    messagingSenderId: '317038982664',
    projectId: 'unionshop-a95a8',
    authDomain: 'unionshop-a95a8.firebaseapp.com',
    storageBucket: 'unionshop-a95a8.firebasestorage.app',
    measurementId: 'G-2YNQGTRPZN',
  );
}
